### ISSUE TITLE
TypeError: Property 'source' of object #<Source> is not a function

### ISSUE THREAD

**Issue by volkanunsal** [webpack/compression-webpack-plugin#6]
I am getting this error with the webpack version 1.9.12 

```
  /Users/newuser/w/citiesense/search/node_modules/webpack/lib/Compiler.js:254
          var content = source.source();
                               ^
  TypeError: Property 'source' of object #<Source> is not a function
      at Tapable.writeOut (/Users/newuser/w/citiesense/search/node_modules/webpack/lib/Compiler.js:254:26)
      at Tapable.<anonymous> (/Users/newuser/w/citiesense/search/node_modules/webpack/lib/Compiler.js:245:20)
      at /Users/newuser/w/citiesense/search/node_modules/webpack/node_modules/async/lib/async.js:122:13
      at _each (/Users/newuser/w/citiesense/search/node_modules/webpack/node_modules/async/lib/async.js:46:13)
      at Object.async.each (/Users/newuser/w/citiesense/search/node_modules/webpack/node_modules/async/lib/async.js:121:9)
      at Tapable.emitFiles (/Users/newuser/w/citiesense/search/node_modules/webpack/lib/Compiler.js:234:20)
      at /Users/newuser/w/citiesense/search/node_modules/webpack/node_modules/mkdirp/index.js:48:26
      at Object.oncomplete (fs.js:108:15)
```

```javascript
// My config
  plugins.push(
    new CompressionPlugin({
        asset: "{file}.gz",
        algorithm: "gzip",
        regExp: /\.js$|\.html$/,
        threshold: 10240,
        minRatio: 0.8
    })
  );
```

**Comment by volkanunsal** [comment]
I forgot to mention that the devtool is set to be `eval`

**Comment by palmerj3** [comment]
@volkanunsal I'm unable to reproduce this. Can you provide more information? Is this still an issue for you?

**Comment by volkanunsal** [comment]
Latest version seems to have fixed the issue.
